/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
////////#include "(null)"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_about (void)
{
  GtkWidget *fenetre_about;
  GtkWidget *dialog_vbox4;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *image66;
  GtkWidget *label33;
  GtkWidget *about_equipe;
  GtkWidget *fixed6;
  GtkWidget *image67;
  GtkWidget *label29;
  GtkWidget *about_techno;
  GtkWidget *fixed7;
  GtkWidget *emploi_texte;
  GtkWidget *label32;
  GtkWidget *image68;
  GtkWidget *about_emploi;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton4;

  fenetre_about = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (fenetre_about), "A propos");
  gtk_window_set_type_hint (GTK_WINDOW (fenetre_about), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (fenetre_about)->vbox;
  gtk_widget_show (dialog_vbox4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), notebook1, TRUE, TRUE, 0);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  image66 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image66);
  gtk_fixed_put (GTK_FIXED (fixed5), image66, 0, 56);
  gtk_widget_set_size_request (image66, 48, 48);

  label33 = gtk_label_new ("<b>Ce projet a \303\251t\303\251 d\303\251velopp\303\251 par :</b>\n\nSt\303\251phane R\303\251gnier\nJordane Guillot\nJonathan-David Schr\303\266der");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 40, 40);
  gtk_widget_set_size_request (label33, 240, 128);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);
  gtk_label_set_angle (GTK_LABEL (label33), 9);

  about_equipe = gtk_label_new ("L'\303\251quipe");
  gtk_widget_show (about_equipe);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), about_equipe);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  image67 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image67);
  gtk_fixed_put (GTK_FIXED (fixed6), image67, 0, 72);
  gtk_widget_set_size_request (image67, 48, 48);

  label29 = gtk_label_new ("<b>Ce projet \303\251crit en langage C \nutilise les librairies suivantes :</b>\n- r\303\251seau : sockets BSD + UWIN\n- interface : GTK 2.0+\n- son : fmod\n<b>et tourne sous Linux et Windows.</b>");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 40, 32);
  gtk_widget_set_size_request (label29, 256, 112);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);
  gtk_label_set_angle (GTK_LABEL (label29), 5);

  about_techno = gtk_label_new ("Les technologies");
  gtk_widget_show (about_techno);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), about_techno);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  emploi_texte = gtk_label_new ("<b>Un peu comme aux dames</b>");
  gtk_widget_show (emploi_texte);
  gtk_fixed_put (GTK_FIXED (fixed7), emploi_texte, 16, 0);
  gtk_widget_set_size_request (emploi_texte, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (emploi_texte), TRUE);
  gtk_label_set_angle (GTK_LABEL (emploi_texte), 5);

  label32 = gtk_label_new ("Un seul pion par camp bouge\n\303\240 chaque tour\nCliquer pour s\303\251lectionner et d\303\251placer\n\n<b>Pour gagner</b>\n\n<b><i>Les loups</i></b> doivent encercler l'agneau\n<b><i>L'agneau</i></b> doit d\303\251passer les loups");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 24, 24);
  gtk_widget_set_size_request (label32, 272, 184);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_CENTER);
  gtk_label_set_angle (GTK_LABEL (label32), 2);

  image68 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image68);
  gtk_fixed_put (GTK_FIXED (fixed7), image68, 16, 40);
  gtk_widget_set_size_request (image68, 48, 48);

  about_emploi = gtk_label_new ("Mode d'emploi");
  gtk_widget_show (about_emploi);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), about_emploi);

  dialog_action_area4 = GTK_DIALOG (fenetre_about)->action_area;
  gtk_widget_show (dialog_action_area4);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (fenetre_about), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, fenetre_about, "fenetre_about");
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (fenetre_about, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_about, image66, "image66");
  GLADE_HOOKUP_OBJECT (fenetre_about, label33, "label33");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_equipe, "about_equipe");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (fenetre_about, image67, "image67");
  GLADE_HOOKUP_OBJECT (fenetre_about, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_techno, "about_techno");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_about, emploi_texte, "emploi_texte");
  GLADE_HOOKUP_OBJECT (fenetre_about, label32, "label32");
  GLADE_HOOKUP_OBJECT (fenetre_about, image68, "image68");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_emploi, "about_emploi");
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (fenetre_about, okbutton4, "okbutton4");

  return fenetre_about;
}

