/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"




int
main (int argc, char *argv[])
{
  GtkWidget *connection_setup;

  gchar *pixmap_dir;


  gtk_set_locale ();
  gtk_init (&argc, &argv);


  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  connection_setup = create_connection_setup ();
  gtk_widget_show (connection_setup);
  g_signal_connect ((gpointer) connection_setup, "destroy", G_CALLBACK(gtk_main_quit),
                    NULL);

  gtk_main ();



  return 0;
}

