/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
//#include "(null)"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_graphiques (void)
{
  GtkWidget *graphiques;
  GtkWidget *fixed2;
  GtkWidget *iconview1;
  GtkWidget *button4;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image59;
  GtkWidget *label8;
  GtkWidget *button1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image60;
  GtkWidget *label9;
  GtkWidget *button2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image57;
  GtkWidget *label6;
  GtkWidget *button3;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image58;
  GtkWidget *label7;
  GtkWidget *button5;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image61;
  GtkWidget *label12;
  GtkWidget *vseparator1;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *comboboxentry1;

  graphiques = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (graphiques), "Th\303\250mes graphiques");
  gtk_window_set_resizable (GTK_WINDOW (graphiques), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (graphiques), "gtk-cdrom");

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (graphiques), fixed2);
  gtk_widget_set_size_request (fixed2, 442, 256);

  iconview1 = gtk_icon_view_new ();
  gtk_widget_show (iconview1);
  gtk_fixed_put (GTK_FIXED (fixed2), iconview1, 24, 40);
  gtk_widget_set_size_request (iconview1, 64, 192);
  gtk_container_set_border_width (GTK_CONTAINER (iconview1), 1);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 112, 88);
  gtk_widget_set_size_request (button4, 176, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image59 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox5), image59, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic ("Choisir comme d\303\251faut");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 112, 136);
  gtk_widget_set_size_request (button1, 176, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image60 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox6), image60, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic ("Importer un th\303\250me...");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 328, 24);
  gtk_widget_set_size_request (button2, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image57 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox3), image57, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic ("Appliquer");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 328, 64);
  gtk_widget_set_size_request (button3, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button3), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image58 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox4), image58, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 328, 104);
  gtk_widget_set_size_request (button5, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button5), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image61 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox7), image61, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic ("Remettre");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator1, 304, 8);
  gtk_widget_set_size_request (vseparator1, 16, 248);

  label10 = gtk_label_new ("<b>Aper\303\247us</b>");
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 24, 8);
  gtk_widget_set_size_request (label10, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label11 = gtk_label_new ("<b>Choix du th\303\250me</b>");
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 112, 8);
  gtk_widget_set_size_request (label11, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 112, 48);
  gtk_widget_set_size_request (comboboxentry1, 179, 26);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "graphiques-campagnes.graph");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "graphiques-montage.graph");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "graphiques-film-horreur.graph");

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (graphiques, graphiques, "graphiques");
  GLADE_HOOKUP_OBJECT (graphiques, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (graphiques, iconview1, "iconview1");
  GLADE_HOOKUP_OBJECT (graphiques, button4, "button4");
  GLADE_HOOKUP_OBJECT (graphiques, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (graphiques, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (graphiques, image59, "image59");
  GLADE_HOOKUP_OBJECT (graphiques, label8, "label8");
  GLADE_HOOKUP_OBJECT (graphiques, button1, "button1");
  GLADE_HOOKUP_OBJECT (graphiques, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (graphiques, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (graphiques, image60, "image60");
  GLADE_HOOKUP_OBJECT (graphiques, label9, "label9");
  GLADE_HOOKUP_OBJECT (graphiques, button2, "button2");
  GLADE_HOOKUP_OBJECT (graphiques, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (graphiques, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (graphiques, image57, "image57");
  GLADE_HOOKUP_OBJECT (graphiques, label6, "label6");
  GLADE_HOOKUP_OBJECT (graphiques, button3, "button3");
  GLADE_HOOKUP_OBJECT (graphiques, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (graphiques, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (graphiques, image58, "image58");
  GLADE_HOOKUP_OBJECT (graphiques, label7, "label7");
  GLADE_HOOKUP_OBJECT (graphiques, button5, "button5");
  GLADE_HOOKUP_OBJECT (graphiques, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (graphiques, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (graphiques, image61, "image61");
  GLADE_HOOKUP_OBJECT (graphiques, label12, "label12");
  GLADE_HOOKUP_OBJECT (graphiques, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (graphiques, label10, "label10");
  GLADE_HOOKUP_OBJECT (graphiques, label11, "label11");
  GLADE_HOOKUP_OBJECT (graphiques, comboboxentry1, "comboboxentry1");

  return graphiques;
}

