/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
//#include "(null)"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_jeu (void)
{
  GtkWidget *jeu;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *image142;
  GtkWidget *menuitem1_menu;
  GtkWidget *nouvelle_partie_locale1;
  GtkWidget *image143;
  GtkWidget *nouvelle_partie_r__seau1;
  GtkWidget *image144;
  GtkWidget *recharger_une_partie1;
  GtkWidget *image145;
  GtkWidget *enregistrer2;
  GtkWidget *enregistrer_sous1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quitter1;
  GtkWidget *menuitem2;
  GtkWidget *image146;
  GtkWidget *menuitem2_menu;
  GtkWidget *coup_pr__c__dent1;
  GtkWidget *image147;
  GtkWidget *arr__ter_la_partie1;
  GtkWidget *image148;
  GtkWidget *prefs;
  GtkWidget *image149;
  GtkWidget *prefs_menu;
  GtkWidget *th__mes_sonores1;
  GtkWidget *image150;
  GtkWidget *th__mes_graphiques1;
  GtkWidget *image151;
  GtkWidget *menuitem4;
  GtkWidget *image152;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *image153;
  GtkWidget *table1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  jeu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (jeu), "Agneau et loups");
  gtk_window_set_position (GTK_WINDOW (jeu), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_icon_name (GTK_WINDOW (jeu), "gtk-about");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (jeu), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_image_menu_item_new_with_mnemonic ("_Partie");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  image142 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image142);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem1), image142);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  nouvelle_partie_locale1 = gtk_image_menu_item_new_with_mnemonic ("Nouvelle partie locale");
  gtk_widget_show (nouvelle_partie_locale1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nouvelle_partie_locale1);
  gtk_widget_add_accelerator (nouvelle_partie_locale1, "activate", accel_group,
                              GDK_N, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image143 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image143);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (nouvelle_partie_locale1), image143);

  nouvelle_partie_r__seau1 = gtk_image_menu_item_new_with_mnemonic ("Nouvelle partie r\303\251seau");
  gtk_widget_show (nouvelle_partie_r__seau1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nouvelle_partie_r__seau1);
  gtk_widget_add_accelerator (nouvelle_partie_r__seau1, "activate", accel_group,
                              GDK_I, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image144 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image144);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (nouvelle_partie_r__seau1), image144);

  recharger_une_partie1 = gtk_image_menu_item_new_with_mnemonic ("Recharger une partie");
  gtk_widget_show (recharger_une_partie1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), recharger_une_partie1);
  gtk_widget_add_accelerator (recharger_une_partie1, "activate", accel_group,
                              GDK_R, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image145 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image145);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (recharger_une_partie1), image145);

  enregistrer2 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (enregistrer2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer2);

  enregistrer_sous1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (enregistrer_sous1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer_sous1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quitter1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quitter1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quitter1);

  menuitem2 = gtk_image_menu_item_new_with_mnemonic ("_Actions");
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  image146 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image146);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem2), image146);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  coup_pr__c__dent1 = gtk_image_menu_item_new_with_mnemonic ("Coup pr\303\251c\303\251dent");
  gtk_widget_show (coup_pr__c__dent1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), coup_pr__c__dent1);
  gtk_widget_add_accelerator (coup_pr__c__dent1, "activate", accel_group,
                              GDK_P, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image147 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image147);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (coup_pr__c__dent1), image147);

  arr__ter_la_partie1 = gtk_image_menu_item_new_with_mnemonic ("Arr\303\252ter la partie");
  gtk_widget_show (arr__ter_la_partie1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), arr__ter_la_partie1);
  gtk_widget_add_accelerator (arr__ter_la_partie1, "activate", accel_group,
                              GDK_X, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image148 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image148);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (arr__ter_la_partie1), image148);

  prefs = gtk_image_menu_item_new_with_mnemonic ("_Pr\303\251f\303\251rences");
  gtk_widget_show (prefs);
  gtk_container_add (GTK_CONTAINER (menubar1), prefs);

  image149 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image149);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (prefs), image149);

  prefs_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (prefs), prefs_menu);

  th__mes_sonores1 = gtk_image_menu_item_new_with_mnemonic ("Th\303\250mes sonores");
  gtk_widget_show (th__mes_sonores1);
  gtk_container_add (GTK_CONTAINER (prefs_menu), th__mes_sonores1);
  gtk_widget_add_accelerator (th__mes_sonores1, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image150 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image150);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (th__mes_sonores1), image150);

  th__mes_graphiques1 = gtk_image_menu_item_new_with_mnemonic ("Th\303\250mes graphiques");
  gtk_widget_show (th__mes_graphiques1);
  gtk_container_add (GTK_CONTAINER (prefs_menu), th__mes_graphiques1);
  gtk_widget_add_accelerator (th__mes_graphiques1, "activate", accel_group,
                              GDK_G, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image151 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image151);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (th__mes_graphiques1), image151);

  menuitem4 = gtk_image_menu_item_new_with_mnemonic ("_?");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  image152 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image152);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem4), image152);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_with_mnemonic ("_A propos");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);
  gtk_widget_add_accelerator (about1, "activate", accel_group,
                              GDK_W, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image153 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image153);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image153);

  table1 = gtk_table_new (10, 10, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) nouvelle_partie_locale1, "activate",
                    G_CALLBACK (on_nouvelle_partie_locale1_activate),
                    NULL);
  g_signal_connect ((gpointer) nouvelle_partie_r__seau1, "activate",
                    G_CALLBACK (on_nouvelle_partie_r__seau1_activate),
                    NULL);
  g_signal_connect ((gpointer) recharger_une_partie1, "activate",
                    G_CALLBACK (on_recharger_une_partie1_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer2, "activate",
                    G_CALLBACK (on_enregistrer2_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer_sous1, "activate",
                    G_CALLBACK (on_enregistrer_sous1_activate),
                    NULL);
  g_signal_connect ((gpointer) quitter1, "activate",
                    G_CALLBACK (on_quitter1_activate),
                    NULL);
  g_signal_connect ((gpointer) coup_pr__c__dent1, "activate",
                    G_CALLBACK (on_coup_pr__c__dent1_activate),
                    NULL);
  g_signal_connect ((gpointer) arr__ter_la_partie1, "activate",
                    G_CALLBACK (on_arr__ter_la_partie1_activate),
                    NULL);
  g_signal_connect ((gpointer) th__mes_sonores1, "activate",
                    G_CALLBACK (on_th__mes_sonores1_activate),
                    NULL);
  g_signal_connect ((gpointer) th__mes_graphiques1, "activate",
                    G_CALLBACK (on_th__mes_graphiques1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (jeu, jeu, "jeu");
  GLADE_HOOKUP_OBJECT (jeu, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (jeu, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (jeu, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (jeu, image142, "image142");
  GLADE_HOOKUP_OBJECT (jeu, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (jeu, nouvelle_partie_locale1, "nouvelle_partie_locale1");
  GLADE_HOOKUP_OBJECT (jeu, image143, "image143");
  GLADE_HOOKUP_OBJECT (jeu, nouvelle_partie_r__seau1, "nouvelle_partie_r__seau1");
  GLADE_HOOKUP_OBJECT (jeu, image144, "image144");
  GLADE_HOOKUP_OBJECT (jeu, recharger_une_partie1, "recharger_une_partie1");
  GLADE_HOOKUP_OBJECT (jeu, image145, "image145");
  GLADE_HOOKUP_OBJECT (jeu, enregistrer2, "enregistrer2");
  GLADE_HOOKUP_OBJECT (jeu, enregistrer_sous1, "enregistrer_sous1");
  GLADE_HOOKUP_OBJECT (jeu, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (jeu, quitter1, "quitter1");
  GLADE_HOOKUP_OBJECT (jeu, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (jeu, image146, "image146");
  GLADE_HOOKUP_OBJECT (jeu, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (jeu, coup_pr__c__dent1, "coup_pr__c__dent1");
  GLADE_HOOKUP_OBJECT (jeu, image147, "image147");
  GLADE_HOOKUP_OBJECT (jeu, arr__ter_la_partie1, "arr__ter_la_partie1");
  GLADE_HOOKUP_OBJECT (jeu, image148, "image148");
  GLADE_HOOKUP_OBJECT (jeu, prefs, "prefs");
  GLADE_HOOKUP_OBJECT (jeu, image149, "image149");
  GLADE_HOOKUP_OBJECT (jeu, prefs_menu, "prefs_menu");
  GLADE_HOOKUP_OBJECT (jeu, th__mes_sonores1, "th__mes_sonores1");
  GLADE_HOOKUP_OBJECT (jeu, image150, "image150");
  GLADE_HOOKUP_OBJECT (jeu, th__mes_graphiques1, "th__mes_graphiques1");
  GLADE_HOOKUP_OBJECT (jeu, image151, "image151");
  GLADE_HOOKUP_OBJECT (jeu, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (jeu, image152, "image152");
  GLADE_HOOKUP_OBJECT (jeu, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (jeu, about1, "about1");
  GLADE_HOOKUP_OBJECT (jeu, image153, "image153");
  GLADE_HOOKUP_OBJECT (jeu, table1, "table1");

  gtk_window_add_accel_group (GTK_WINDOW (jeu), accel_group);

  return jeu;
}

