/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_jeu (void)
{
  GtkWidget *jeu;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *image142;
  GtkWidget *menuitem1_menu;
  GtkWidget *nouvelle_partie_locale1;
  GtkWidget *image143;
  GtkWidget *nouvelle_partie_r__seau1;
  GtkWidget *image144;
  GtkWidget *recharger_une_partie1;
  GtkWidget *image145;
  GtkWidget *enregistrer2;
  GtkWidget *enregistrer_sous1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quitter1;
  GtkWidget *menuitem2;
  GtkWidget *image146;
  GtkWidget *menuitem2_menu;
  GtkWidget *coup_pr__c__dent1;
  GtkWidget *image147;
  GtkWidget *arr__ter_la_partie1;
  GtkWidget *image148;
  GtkWidget *prefs;
  GtkWidget *image149;
  GtkWidget *prefs_menu;
  GtkWidget *th__mes_sonores1;
  GtkWidget *image150;
  GtkWidget *th__mes_graphiques1;
  GtkWidget *image151;
  GtkWidget *menuitem4;
  GtkWidget *image152;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *image153;
  GtkWidget *table1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  jeu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (jeu), "Agneau et loups");
  gtk_window_set_icon_name (GTK_WINDOW (jeu), "gtk-about");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (jeu), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_image_menu_item_new_with_mnemonic ("_Partie");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  image142 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image142);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem1), image142);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  nouvelle_partie_locale1 = gtk_image_menu_item_new_with_mnemonic ("Nouvelle partie locale");
  gtk_widget_show (nouvelle_partie_locale1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nouvelle_partie_locale1);
  gtk_widget_add_accelerator (nouvelle_partie_locale1, "activate", accel_group,
                              GDK_N, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image143 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image143);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (nouvelle_partie_locale1), image143);

  nouvelle_partie_r__seau1 = gtk_image_menu_item_new_with_mnemonic ("Nouvelle partie r\303\251seau");
  gtk_widget_show (nouvelle_partie_r__seau1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nouvelle_partie_r__seau1);
  gtk_widget_add_accelerator (nouvelle_partie_r__seau1, "activate", accel_group,
                              GDK_I, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image144 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image144);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (nouvelle_partie_r__seau1), image144);

  recharger_une_partie1 = gtk_image_menu_item_new_with_mnemonic ("Recharger une partie");
  gtk_widget_show (recharger_une_partie1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), recharger_une_partie1);
  gtk_widget_add_accelerator (recharger_une_partie1, "activate", accel_group,
                              GDK_R, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image145 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image145);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (recharger_une_partie1), image145);

  enregistrer2 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (enregistrer2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer2);

  enregistrer_sous1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (enregistrer_sous1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer_sous1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quitter1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quitter1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quitter1);

  menuitem2 = gtk_image_menu_item_new_with_mnemonic ("_Actions");
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  image146 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image146);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem2), image146);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  coup_pr__c__dent1 = gtk_image_menu_item_new_with_mnemonic ("Coup pr\303\251c\303\251dent");
  gtk_widget_show (coup_pr__c__dent1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), coup_pr__c__dent1);
  gtk_widget_add_accelerator (coup_pr__c__dent1, "activate", accel_group,
                              GDK_P, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image147 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image147);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (coup_pr__c__dent1), image147);

  arr__ter_la_partie1 = gtk_image_menu_item_new_with_mnemonic ("Arr\303\252ter la partie");
  gtk_widget_show (arr__ter_la_partie1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), arr__ter_la_partie1);
  gtk_widget_add_accelerator (arr__ter_la_partie1, "activate", accel_group,
                              GDK_X, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image148 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image148);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (arr__ter_la_partie1), image148);

  prefs = gtk_image_menu_item_new_with_mnemonic ("_Pr\303\251f\303\251rences");
  gtk_widget_show (prefs);
  gtk_container_add (GTK_CONTAINER (menubar1), prefs);

  image149 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image149);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (prefs), image149);

  prefs_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (prefs), prefs_menu);

  th__mes_sonores1 = gtk_image_menu_item_new_with_mnemonic ("Th\303\250mes sonores");
  gtk_widget_show (th__mes_sonores1);
  gtk_container_add (GTK_CONTAINER (prefs_menu), th__mes_sonores1);
  gtk_widget_add_accelerator (th__mes_sonores1, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image150 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image150);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (th__mes_sonores1), image150);

  th__mes_graphiques1 = gtk_image_menu_item_new_with_mnemonic ("Th\303\250mes graphiques");
  gtk_widget_show (th__mes_graphiques1);
  gtk_container_add (GTK_CONTAINER (prefs_menu), th__mes_graphiques1);
  gtk_widget_add_accelerator (th__mes_graphiques1, "activate", accel_group,
                              GDK_G, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image151 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image151);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (th__mes_graphiques1), image151);

  menuitem4 = gtk_image_menu_item_new_with_mnemonic ("_?");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  image152 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image152);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem4), image152);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_with_mnemonic ("_A propos");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);
  gtk_widget_add_accelerator (about1, "activate", accel_group,
                              GDK_W, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image153 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image153);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image153);

  table1 = gtk_table_new (10, 10, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) nouvelle_partie_locale1, "activate",
                    G_CALLBACK (on_nouvelle_partie_locale1_activate),
                    NULL);
  g_signal_connect ((gpointer) nouvelle_partie_r__seau1, "activate",
                    G_CALLBACK (on_nouvelle_partie_r__seau1_activate),
                    NULL);
  g_signal_connect ((gpointer) recharger_une_partie1, "activate",
                    G_CALLBACK (on_recharger_une_partie1_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer2, "activate",
                    G_CALLBACK (on_enregistrer2_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer_sous1, "activate",
                    G_CALLBACK (on_enregistrer_sous1_activate),
                    NULL);
  g_signal_connect ((gpointer) quitter1, "activate",
                    G_CALLBACK (on_quitter1_activate),
                    NULL);
  g_signal_connect ((gpointer) coup_pr__c__dent1, "activate",
                    G_CALLBACK (on_coup_pr__c__dent1_activate),
                    NULL);
  g_signal_connect ((gpointer) arr__ter_la_partie1, "activate",
                    G_CALLBACK (on_arr__ter_la_partie1_activate),
                    NULL);
  g_signal_connect ((gpointer) th__mes_sonores1, "activate",
                    G_CALLBACK (on_th__mes_sonores1_activate),
                    NULL);
  g_signal_connect ((gpointer) th__mes_graphiques1, "activate",
                    G_CALLBACK (on_th__mes_graphiques1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (jeu, jeu, "jeu");
  GLADE_HOOKUP_OBJECT (jeu, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (jeu, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (jeu, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (jeu, image142, "image142");
  GLADE_HOOKUP_OBJECT (jeu, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (jeu, nouvelle_partie_locale1, "nouvelle_partie_locale1");
  GLADE_HOOKUP_OBJECT (jeu, image143, "image143");
  GLADE_HOOKUP_OBJECT (jeu, nouvelle_partie_r__seau1, "nouvelle_partie_r__seau1");
  GLADE_HOOKUP_OBJECT (jeu, image144, "image144");
  GLADE_HOOKUP_OBJECT (jeu, recharger_une_partie1, "recharger_une_partie1");
  GLADE_HOOKUP_OBJECT (jeu, image145, "image145");
  GLADE_HOOKUP_OBJECT (jeu, enregistrer2, "enregistrer2");
  GLADE_HOOKUP_OBJECT (jeu, enregistrer_sous1, "enregistrer_sous1");
  GLADE_HOOKUP_OBJECT (jeu, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (jeu, quitter1, "quitter1");
  GLADE_HOOKUP_OBJECT (jeu, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (jeu, image146, "image146");
  GLADE_HOOKUP_OBJECT (jeu, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (jeu, coup_pr__c__dent1, "coup_pr__c__dent1");
  GLADE_HOOKUP_OBJECT (jeu, image147, "image147");
  GLADE_HOOKUP_OBJECT (jeu, arr__ter_la_partie1, "arr__ter_la_partie1");
  GLADE_HOOKUP_OBJECT (jeu, image148, "image148");
  GLADE_HOOKUP_OBJECT (jeu, prefs, "prefs");
  GLADE_HOOKUP_OBJECT (jeu, image149, "image149");
  GLADE_HOOKUP_OBJECT (jeu, prefs_menu, "prefs_menu");
  GLADE_HOOKUP_OBJECT (jeu, th__mes_sonores1, "th__mes_sonores1");
  GLADE_HOOKUP_OBJECT (jeu, image150, "image150");
  GLADE_HOOKUP_OBJECT (jeu, th__mes_graphiques1, "th__mes_graphiques1");
  GLADE_HOOKUP_OBJECT (jeu, image151, "image151");
  GLADE_HOOKUP_OBJECT (jeu, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (jeu, image152, "image152");
  GLADE_HOOKUP_OBJECT (jeu, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (jeu, about1, "about1");
  GLADE_HOOKUP_OBJECT (jeu, image153, "image153");
  GLADE_HOOKUP_OBJECT (jeu, table1, "table1");

  gtk_window_add_accel_group (GTK_WINDOW (jeu), accel_group);

  return jeu;
}

GtkWidget*
create_connection (void)
{
  GtkWidget *connection;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed1;
  GtkWidget *entry2;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *label1;
  GtkWidget *entry7;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label24;
  GtkWidget *radiobutton2;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image56;
  GtkWidget *label5;
  GtkWidget *okbutton1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image55;
  GtkWidget *label4;

  connection = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (connection), "Partie R\303\251seau");
  gtk_window_set_icon_name (GTK_WINDOW (connection), "gtk-dialog-info");
  gtk_window_set_type_hint (GTK_WINDOW (connection), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (connection)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed1, TRUE, TRUE, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 72, 48);
  gtk_widget_set_size_request (entry2, 158, 26);
  gtk_entry_set_text (GTK_ENTRY (entry2), "Bob");

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, "J'h\303\251berge la partie");
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 40, 88);
  gtk_widget_set_size_request (radiobutton1, 152, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 72, 200);
  gtk_widget_set_size_request (entry3, 158, 26);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed1), entry4, 72, 240);
  gtk_widget_set_size_request (entry4, 158, 26);

  label1 = gtk_label_new ("Mon nom de joueur :");
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 40, 16);
  gtk_widget_set_size_request (label1, 152, 26);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed1), entry7, 80, 120);
  gtk_widget_set_size_request (entry7, 158, 26);
  gtk_entry_set_text (GTK_ENTRY (entry7), "5010");

  label2 = gtk_label_new ("IP");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 200);
  gtk_widget_set_size_request (label2, 36, 18);

  label3 = gtk_label_new ("Port");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 32, 240);
  gtk_widget_set_size_request (label3, 36, 18);

  label24 = gtk_label_new ("Port");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed1), label24, 40, 120);
  gtk_widget_set_size_request (label24, 36, 18);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, "Je me connecte chez quelqu'un");
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 32, 160);
  gtk_widget_set_size_request (radiobutton2, 240, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  dialog_action_area1 = GTK_DIALOG (connection)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new ();
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (connection), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (cancelbutton1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image56 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox2), image56, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  okbutton1 = gtk_button_new ();
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (connection), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (okbutton1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image55 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox1), image55, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic ("C'est parti !");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connection, connection, "connection");
  GLADE_HOOKUP_OBJECT_NO_REF (connection, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (connection, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (connection, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (connection, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (connection, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (connection, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (connection, label1, "label1");
  GLADE_HOOKUP_OBJECT (connection, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (connection, label2, "label2");
  GLADE_HOOKUP_OBJECT (connection, label3, "label3");
  GLADE_HOOKUP_OBJECT (connection, label24, "label24");
  GLADE_HOOKUP_OBJECT (connection, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT_NO_REF (connection, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (connection, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (connection, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (connection, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (connection, image56, "image56");
  GLADE_HOOKUP_OBJECT (connection, label5, "label5");
  GLADE_HOOKUP_OBJECT (connection, okbutton1, "okbutton1");
  GLADE_HOOKUP_OBJECT (connection, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (connection, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (connection, image55, "image55");
  GLADE_HOOKUP_OBJECT (connection, label4, "label4");

  return connection;
}

GtkWidget*
create_son (void)
{
  GtkWidget *son;
  GtkWidget *fixed2;
  GtkWidget *iconview1;
  GtkWidget *button4;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image59;
  GtkWidget *label8;
  GtkWidget *button1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image60;
  GtkWidget *label9;
  GtkWidget *button2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image57;
  GtkWidget *label6;
  GtkWidget *button3;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image58;
  GtkWidget *label7;
  GtkWidget *button5;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image61;
  GtkWidget *label12;
  GtkWidget *vseparator1;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *comboboxentry1;

  son = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (son), "Th\303\250mes sonores");
  gtk_window_set_resizable (GTK_WINDOW (son), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (son), "gtk-cdrom");

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (son), fixed2);
  gtk_widget_set_size_request (fixed2, 442, 256);

  iconview1 = gtk_icon_view_new ();
  gtk_widget_show (iconview1);
  gtk_fixed_put (GTK_FIXED (fixed2), iconview1, 24, 40);
  gtk_widget_set_size_request (iconview1, 64, 192);
  gtk_container_set_border_width (GTK_CONTAINER (iconview1), 1);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 112, 88);
  gtk_widget_set_size_request (button4, 176, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image59 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox5), image59, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic ("Choisir comme d\303\251faut");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 112, 136);
  gtk_widget_set_size_request (button1, 176, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image60 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox6), image60, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic ("Importer un th\303\250me...");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 328, 24);
  gtk_widget_set_size_request (button2, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image57 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox3), image57, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic ("Appliquer");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 328, 64);
  gtk_widget_set_size_request (button3, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button3), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image58 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox4), image58, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 328, 104);
  gtk_widget_set_size_request (button5, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button5), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image61 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox7), image61, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic ("Remettre");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator1, 304, 8);
  gtk_widget_set_size_request (vseparator1, 16, 248);

  label10 = gtk_label_new ("<b>Aper\303\247us</b>");
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 24, 8);
  gtk_widget_set_size_request (label10, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label11 = gtk_label_new ("<b>Choix du th\303\250me</b>");
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 112, 8);
  gtk_widget_set_size_request (label11, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 112, 48);
  gtk_widget_set_size_request (comboboxentry1, 179, 26);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "sons-campagnes.son");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "sons-montage.son");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "sons-film-horreur.son");

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (son, son, "son");
  GLADE_HOOKUP_OBJECT (son, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (son, iconview1, "iconview1");
  GLADE_HOOKUP_OBJECT (son, button4, "button4");
  GLADE_HOOKUP_OBJECT (son, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (son, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (son, image59, "image59");
  GLADE_HOOKUP_OBJECT (son, label8, "label8");
  GLADE_HOOKUP_OBJECT (son, button1, "button1");
  GLADE_HOOKUP_OBJECT (son, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (son, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (son, image60, "image60");
  GLADE_HOOKUP_OBJECT (son, label9, "label9");
  GLADE_HOOKUP_OBJECT (son, button2, "button2");
  GLADE_HOOKUP_OBJECT (son, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (son, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (son, image57, "image57");
  GLADE_HOOKUP_OBJECT (son, label6, "label6");
  GLADE_HOOKUP_OBJECT (son, button3, "button3");
  GLADE_HOOKUP_OBJECT (son, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (son, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (son, image58, "image58");
  GLADE_HOOKUP_OBJECT (son, label7, "label7");
  GLADE_HOOKUP_OBJECT (son, button5, "button5");
  GLADE_HOOKUP_OBJECT (son, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (son, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (son, image61, "image61");
  GLADE_HOOKUP_OBJECT (son, label12, "label12");
  GLADE_HOOKUP_OBJECT (son, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (son, label10, "label10");
  GLADE_HOOKUP_OBJECT (son, label11, "label11");
  GLADE_HOOKUP_OBJECT (son, comboboxentry1, "comboboxentry1");

  return son;
}

GtkWidget*
create_jeusimple (void)
{
  GtkWidget *jeusimple;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed3;
  GtkWidget *entry5;
  GtkWidget *label13;
  GtkWidget *label16;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *entry6;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *label17;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *label14;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *label15;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image63;
  GtkWidget *label19;
  GtkWidget *okbutton2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image62;
  GtkWidget *label18;

  jeusimple = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (jeusimple), "Partie un ou deux joueurs");
  gtk_window_set_icon_name (GTK_WINDOW (jeusimple), "gtk-dialog-info");
  gtk_window_set_type_hint (GTK_WINDOW (jeusimple), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (jeusimple)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed3, TRUE, TRUE, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 128, 80);
  gtk_widget_set_size_request (entry5, 158, 26);

  label13 = gtk_label_new ("<b>Agneau</b>");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 40, 32);
  gtk_widget_set_size_request (label13, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label16 = gtk_label_new ("<b>Loups</b>");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 40, 120);
  gtk_widget_set_size_request (label16, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 56, 56);
  gtk_widget_set_size_request (radiobutton4, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 128, 176);
  gtk_widget_set_size_request (entry6, 158, 26);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton7, 64, 200);
  gtk_widget_set_size_request (radiobutton7, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label17 = gtk_label_new ("Surnom :");
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 64, 176);
  gtk_widget_set_size_request (label17, 64, 16);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 56, 104);
  gtk_widget_set_size_request (radiobutton3, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label14 = gtk_label_new ("Surnom :");
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 56, 80);
  gtk_widget_set_size_request (label14, 64, 16);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5, 64, 144);
  gtk_widget_set_size_request (radiobutton5, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label15 = gtk_label_new ("<b>Choisis ton camp et entre ton nom</b>");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 48, 8);
  gtk_widget_set_size_request (label15, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  dialog_action_area2 = GTK_DIALOG (jeusimple)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new ();
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (cancelbutton2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image63 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox9), image63, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  okbutton2 = gtk_button_new ();
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (okbutton2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image62 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox8), image62, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic ("C'est parti !");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, jeusimple, "jeusimple");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (jeusimple, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (jeusimple, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (jeusimple, label13, "label13");
  GLADE_HOOKUP_OBJECT (jeusimple, label16, "label16");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (jeusimple, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (jeusimple, label17, "label17");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (jeusimple, label14, "label14");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (jeusimple, label15, "label15");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (jeusimple, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (jeusimple, image63, "image63");
  GLADE_HOOKUP_OBJECT (jeusimple, label19, "label19");
  GLADE_HOOKUP_OBJECT (jeusimple, okbutton2, "okbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (jeusimple, image62, "image62");
  GLADE_HOOKUP_OBJECT (jeusimple, label18, "label18");

  return jeusimple;
}

GtkWidget*
create_reseau_choix_joueur (void)
{
  GtkWidget *reseau_choix_joueur;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed4;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *radiobutton9;
  GtkWidget *label20;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image65;
  GtkWidget *label23;
  GtkWidget *okbutton3;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image64;
  GtkWidget *label22;

  reseau_choix_joueur = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (reseau_choix_joueur), "Choix du joueur");
  gtk_window_set_icon_name (GTK_WINDOW (reseau_choix_joueur), "gtk-about");
  gtk_window_set_type_hint (GTK_WINDOW (reseau_choix_joueur), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (reseau_choix_joueur)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed4, TRUE, TRUE, 0);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, "Agneau");
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton8, 64, 64);
  gtk_widget_set_size_request (radiobutton8, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, "Loups");
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton9, 64, 96);
  gtk_widget_set_size_request (radiobutton9, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  label20 = gtk_label_new ("<b>Tu as l'avantage de choisir ton camp</b>");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 24, 16);
  gtk_widget_set_size_request (label20, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label20), TRUE);

  dialog_action_area3 = GTK_DIALOG (reseau_choix_joueur)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new ();
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (reseau_choix_joueur), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (cancelbutton3), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image65 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox11), image65, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic ("Abandonner");
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  okbutton3 = gtk_button_new ();
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (reseau_choix_joueur), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (okbutton3), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image64 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox10), image64, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic ("C'est bon !");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox10), label22, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, reseau_choix_joueur, "reseau_choix_joueur");
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label20, "label20");
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, image65, "image65");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label23, "label23");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, okbutton3, "okbutton3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, image64, "image64");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label22, "label22");

  return reseau_choix_joueur;
}

GtkWidget*
create_fenetre_about (void)
{
  GtkWidget *fenetre_about;
  GtkWidget *dialog_vbox4;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *image66;
  GtkWidget *label33;
  GtkWidget *about_equipe;
  GtkWidget *fixed6;
  GtkWidget *image67;
  GtkWidget *label29;
  GtkWidget *about_techno;
  GtkWidget *fixed7;
  GtkWidget *emploi_texte;
  GtkWidget *label32;
  GtkWidget *about_emploi;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton4;

  fenetre_about = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (fenetre_about), "A propos");
  gtk_window_set_type_hint (GTK_WINDOW (fenetre_about), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (fenetre_about)->vbox;
  gtk_widget_show (dialog_vbox4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), notebook1, TRUE, TRUE, 0);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  image66 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image66);
  gtk_fixed_put (GTK_FIXED (fixed5), image66, 0, 56);
  gtk_widget_set_size_request (image66, 48, 48);

  label33 = gtk_label_new ("<b>Ce projet a \303\251t\303\251 d\303\251velopp\303\251 par :</b>\n\nSt\303\251phane R\303\251gnier\nJordane Guillot\nJonathan-David Schr\303\266der");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 48, 40);
  gtk_widget_set_size_request (label33, 232, 104);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  about_equipe = gtk_label_new ("L'\303\251quipe");
  gtk_widget_show (about_equipe);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), about_equipe);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  image67 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image67);
  gtk_fixed_put (GTK_FIXED (fixed6), image67, 0, 72);
  gtk_widget_set_size_request (image67, 48, 48);

  label29 = gtk_label_new ("<b>Ce projet \303\251crit en langage C \nutilise les librairies suivantes :</b>\n- r\303\251seau : sockets BSD\n- interface : GTK 2.0+\n- son : fmod\n<b>et tourne sous Linux et Windows.</b>");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 40, 32);
  gtk_widget_set_size_request (label29, 256, 112);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);
  gtk_label_set_angle (GTK_LABEL (label29), 5);

  about_techno = gtk_label_new ("Les technologies");
  gtk_widget_show (about_techno);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), about_techno);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  emploi_texte = gtk_label_new ("<b>Un peu comme aux dames</b>");
  gtk_widget_show (emploi_texte);
  gtk_fixed_put (GTK_FIXED (fixed7), emploi_texte, 16, 0);
  gtk_widget_set_size_request (emploi_texte, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (emploi_texte), TRUE);
  gtk_label_set_angle (GTK_LABEL (emploi_texte), 5);

  label32 = gtk_label_new ("Un seul pion par camp bouge\n\303\240 chaque tour\nCliquer pour s\303\251lectionner et d\303\251placer\n\n<b>Pour gagner</b>\n\n<b><i>Les loups</i></b> doivent encercler l'agneau\n<b><i>L'agneau</i></b> doit d\303\251passer les loups");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 16, 24);
  gtk_widget_set_size_request (label32, 256, 136);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_CENTER);
  gtk_label_set_angle (GTK_LABEL (label32), 2);

  about_emploi = gtk_label_new ("Mode d'emploi");
  gtk_widget_show (about_emploi);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), about_emploi);

  dialog_action_area4 = GTK_DIALOG (fenetre_about)->action_area;
  gtk_widget_show (dialog_action_area4);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (fenetre_about), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, fenetre_about, "fenetre_about");
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (fenetre_about, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_about, image66, "image66");
  GLADE_HOOKUP_OBJECT (fenetre_about, label33, "label33");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_equipe, "about_equipe");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (fenetre_about, image67, "image67");
  GLADE_HOOKUP_OBJECT (fenetre_about, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_techno, "about_techno");
  GLADE_HOOKUP_OBJECT (fenetre_about, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_about, emploi_texte, "emploi_texte");
  GLADE_HOOKUP_OBJECT (fenetre_about, label32, "label32");
  GLADE_HOOKUP_OBJECT (fenetre_about, about_emploi, "about_emploi");
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_about, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (fenetre_about, okbutton4, "okbutton4");

  return fenetre_about;
}

