/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
//#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *jeu;
  GtkWidget *connection;
  GtkWidget *son;
  GtkWidget *jeusimple;
  GtkWidget *reseau_choix_joueur;
  GtkWidget *fenetre_about;

  gtk_set_locale ();
  gtk_init (&argc, &argv);

//  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  jeu = create_jeu ();
  gtk_widget_show (jeu);
  connection = create_connection ();
  gtk_widget_show (connection);
  son = create_son ();
  gtk_widget_show (son);
  jeusimple = create_jeusimple ();
  gtk_widget_show (jeusimple);
  reseau_choix_joueur = create_reseau_choix_joueur ();
  gtk_widget_show (reseau_choix_joueur);
  fenetre_about = create_fenetre_about ();
  gtk_widget_show (fenetre_about);

  gtk_main ();
  return 0;
}

