/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "(null)"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_jeusimple (void)
{
  GtkWidget *jeusimple;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed3;
  GtkWidget *nom_agneau_box;
  GtkWidget *label14;
  GtkWidget *nom_agneau;
  GtkWidget *nom_loups_box;
  GtkWidget *label22;
  GtkWidget *nom_loups;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label13;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *pos_agneau_bas;
  GSList *pos_agneau_bas_group = NULL;
  GtkWidget *agneau_radio_ordi;
  GSList *agneau_radio_ordi_group = NULL;
  GtkWidget *loups_radio_ordi;
  GSList *loups_radio_ordi_group = NULL;
  GtkWidget *pos_agneau_haut;
  GtkWidget *loups_radio_joueur;
  GtkWidget *agneau_radio_joueur;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image63;
  GtkWidget *label19;
  GtkWidget *okbutton2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image62;
  GtkWidget *label18;

  jeusimple = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (jeusimple), "Partie un ou deux joueurs");
  gtk_window_set_icon_name (GTK_WINDOW (jeusimple), "gtk-dialog-info");
  gtk_window_set_type_hint (GTK_WINDOW (jeusimple), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (jeusimple)->vbox;
  gtk_widget_show (dialog_vbox2);
  gtk_widget_set_size_request (dialog_vbox2, 333, 372);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed3, TRUE, TRUE, 0);

  nom_agneau_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (nom_agneau_box);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_agneau_box, 77, 85);
  gtk_widget_set_size_request (nom_agneau_box, 32, 16);

  label14 = gtk_label_new ("Surnom :");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (nom_agneau_box), label14, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label14, 64, 16);

  nom_agneau = gtk_entry_new ();
  gtk_widget_show (nom_agneau);
  gtk_box_pack_start (GTK_BOX (nom_agneau_box), nom_agneau, FALSE, FALSE, 0);
  gtk_widget_set_size_request (nom_agneau, 158, 26);

  nom_loups_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (nom_loups_box);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_loups_box, 77, 173);
  gtk_widget_set_size_request (nom_loups_box, 32, 16);
  gtk_widget_set_sensitive (nom_loups_box, FALSE);

  label22 = gtk_label_new ("Surnom :");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (nom_loups_box), label22, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label22, 64, 16);

  nom_loups = gtk_entry_new ();
  gtk_widget_show (nom_loups);
  gtk_box_pack_start (GTK_BOX (nom_loups_box), nom_loups, FALSE, FALSE, 0);
  gtk_widget_set_size_request (nom_loups, 158, 26);

  label15 = gtk_label_new ("<b>Choisis ton camp et entre ton nom</b>");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 24, 8);
  gtk_widget_set_size_request (label15, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new ("<b>Loups</b>");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 30, 120);
  gtk_widget_set_size_request (label16, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label13 = gtk_label_new ("<b>Agneau</b>");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 30, 32);
  gtk_widget_set_size_request (label13, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label24 = gtk_label_new ("L'agneau commence :");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 56, 256);
  gtk_widget_set_size_request (label24, 152, 16);

  label23 = gtk_label_new ("<b>Positionnement</b>");
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 30, 224);
  gtk_widget_set_size_request (label23, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  pos_agneau_bas = gtk_radio_button_new_with_mnemonic (NULL, "en haut");
  gtk_widget_show (pos_agneau_bas);
  gtk_fixed_put (GTK_FIXED (fixed3), pos_agneau_bas, 80, 304);
  gtk_widget_set_size_request (pos_agneau_bas, 105, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (pos_agneau_bas), pos_agneau_bas_group);
  pos_agneau_bas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (pos_agneau_bas));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pos_agneau_bas), TRUE);

  agneau_radio_ordi = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (agneau_radio_ordi);
  gtk_fixed_put (GTK_FIXED (fixed3), agneau_radio_ordi, 56, 104);
  gtk_widget_set_size_request (agneau_radio_ordi, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (agneau_radio_ordi), agneau_radio_ordi_group);
  agneau_radio_ordi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (agneau_radio_ordi));

  loups_radio_ordi = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (loups_radio_ordi);
  gtk_fixed_put (GTK_FIXED (fixed3), loups_radio_ordi, 56, 200);
  gtk_widget_set_size_request (loups_radio_ordi, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (loups_radio_ordi), loups_radio_ordi_group);
  loups_radio_ordi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (loups_radio_ordi));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (loups_radio_ordi), TRUE);

  pos_agneau_haut = gtk_radio_button_new_with_mnemonic (NULL, "en bas");
  gtk_widget_show (pos_agneau_haut);
  gtk_fixed_put (GTK_FIXED (fixed3), pos_agneau_haut, 80, 280);
  gtk_widget_set_size_request (pos_agneau_haut, 105, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (pos_agneau_haut), pos_agneau_bas_group);
  pos_agneau_bas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (pos_agneau_haut));

  loups_radio_joueur = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (loups_radio_joueur);
  gtk_fixed_put (GTK_FIXED (fixed3), loups_radio_joueur, 56, 144);
  gtk_widget_set_size_request (loups_radio_joueur, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (loups_radio_joueur), loups_radio_ordi_group);
  loups_radio_ordi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (loups_radio_joueur));

  agneau_radio_joueur = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (agneau_radio_joueur);
  gtk_fixed_put (GTK_FIXED (fixed3), agneau_radio_joueur, 56, 56);
  gtk_widget_set_size_request (agneau_radio_joueur, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (agneau_radio_joueur), agneau_radio_ordi_group);
  agneau_radio_ordi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (agneau_radio_joueur));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (agneau_radio_joueur), TRUE);

  dialog_action_area2 = GTK_DIALOG (jeusimple)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new ();
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (cancelbutton2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image63 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox9), image63, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  okbutton2 = gtk_button_new ();
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (okbutton2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image62 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox8), image62, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic ("C'est parti !");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  g_signal_connect_swapped ((gpointer) agneau_radio_ordi, "toggled",
                            G_CALLBACK (on_agneau_radio_ordi_toggled),
                            GTK_OBJECT (nom_agneau_box));
  g_signal_connect_swapped ((gpointer) loups_radio_ordi, "toggled",
                            G_CALLBACK (on_loups_radio_ordi_toggled),
                            GTK_OBJECT (nom_loups_box));
  g_signal_connect_swapped ((gpointer) loups_radio_joueur, "toggled",
                            G_CALLBACK (on_loups_radio_joueur_toggled),
                            GTK_OBJECT (nom_loups_box));
  g_signal_connect_swapped ((gpointer) agneau_radio_joueur, "toggled",
                            G_CALLBACK (on_agneau_radio_joueur_toggled),
                            GTK_OBJECT (nom_agneau_box));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, jeusimple, "jeusimple");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (jeusimple, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (jeusimple, nom_agneau_box, "nom_agneau_box");
  GLADE_HOOKUP_OBJECT (jeusimple, label14, "label14");
  GLADE_HOOKUP_OBJECT (jeusimple, nom_agneau, "nom_agneau");
  GLADE_HOOKUP_OBJECT (jeusimple, nom_loups_box, "nom_loups_box");
  GLADE_HOOKUP_OBJECT (jeusimple, label22, "label22");
  GLADE_HOOKUP_OBJECT (jeusimple, nom_loups, "nom_loups");
  GLADE_HOOKUP_OBJECT (jeusimple, label15, "label15");
  GLADE_HOOKUP_OBJECT (jeusimple, label16, "label16");
  GLADE_HOOKUP_OBJECT (jeusimple, label13, "label13");
  GLADE_HOOKUP_OBJECT (jeusimple, label24, "label24");
  GLADE_HOOKUP_OBJECT (jeusimple, label23, "label23");
  GLADE_HOOKUP_OBJECT (jeusimple, pos_agneau_bas, "pos_agneau_bas");
  GLADE_HOOKUP_OBJECT (jeusimple, agneau_radio_ordi, "agneau_radio_ordi");
  GLADE_HOOKUP_OBJECT (jeusimple, loups_radio_ordi, "loups_radio_ordi");
  GLADE_HOOKUP_OBJECT (jeusimple, pos_agneau_haut, "pos_agneau_haut");
  GLADE_HOOKUP_OBJECT (jeusimple, loups_radio_joueur, "loups_radio_joueur");
  GLADE_HOOKUP_OBJECT (jeusimple, agneau_radio_joueur, "agneau_radio_joueur");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (jeusimple, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (jeusimple, image63, "image63");
  GLADE_HOOKUP_OBJECT (jeusimple, label19, "label19");
  GLADE_HOOKUP_OBJECT (jeusimple, okbutton2, "okbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (jeusimple, image62, "image62");
  GLADE_HOOKUP_OBJECT (jeusimple, label18, "label18");

  return jeusimple;
}

