/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
//#include "(null)"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_reseau_choix_joueur (void)
{
  GtkWidget *reseau_choix_joueur;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed4;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *radiobutton9;
  GtkWidget *label20;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image65;
  GtkWidget *label23;
  GtkWidget *okbutton3;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image64;
  GtkWidget *label22;

  reseau_choix_joueur = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (reseau_choix_joueur), "Choix du joueur");
  gtk_window_set_icon_name (GTK_WINDOW (reseau_choix_joueur), "gtk-about");
  gtk_window_set_type_hint (GTK_WINDOW (reseau_choix_joueur), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (reseau_choix_joueur)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed4, TRUE, TRUE, 0);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, "Agneau");
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton8, 64, 64);
  gtk_widget_set_size_request (radiobutton8, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, "Loups");
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton9, 64, 96);
  gtk_widget_set_size_request (radiobutton9, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  label20 = gtk_label_new ("<b>Tu as l'avantage de choisir ton camp</b>");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 24, 16);
  gtk_widget_set_size_request (label20, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label20), TRUE);

  dialog_action_area3 = GTK_DIALOG (reseau_choix_joueur)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new ();
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (reseau_choix_joueur), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (cancelbutton3), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image65 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox11), image65, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic ("Abandonner");
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  okbutton3 = gtk_button_new ();
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (reseau_choix_joueur), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (okbutton3), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image64 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox10), image64, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic ("C'est bon !");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox10), label22, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, reseau_choix_joueur, "reseau_choix_joueur");
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label20, "label20");
  GLADE_HOOKUP_OBJECT_NO_REF (reseau_choix_joueur, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, image65, "image65");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label23, "label23");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, okbutton3, "okbutton3");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, image64, "image64");
  GLADE_HOOKUP_OBJECT (reseau_choix_joueur, label22, "label22");

  return reseau_choix_joueur;
}

