/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"


#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_jeusimple (void)
{
  GtkWidget *jeusimple;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed3;
  GtkWidget *nom_agneau_box;
  GtkWidget *label14;
  GtkWidget *entry5;
  GtkWidget *hbox11;
  GtkWidget *label22;
  GtkWidget *entry6;
  GtkWidget *label16;
  GtkWidget *label13;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *label15;
  GtkWidget *radiobutton4;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image63;
  GtkWidget *label19;
  GtkWidget *okbutton2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image62;
  GtkWidget *label18;

  jeusimple = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (jeusimple), "Partie un ou deux joueurs");
  //gtk_window_set_icon_name (GTK_WINDOW (jeusimple), "gtk-dialog-info");
  gtk_window_set_type_hint (GTK_WINDOW (jeusimple), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (jeusimple)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed3, TRUE, TRUE, 0);

  nom_agneau_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (nom_agneau_box);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_agneau_box, 77, 85);
  gtk_widget_set_size_request (nom_agneau_box, 32, 16);

  label14 = gtk_label_new ("Surnom :");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (nom_agneau_box), label14, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label14, 64, 16);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (nom_agneau_box), entry5, FALSE, FALSE, 0);
  gtk_widget_set_size_request (entry5, 158, 26);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_fixed_put (GTK_FIXED (fixed3), hbox11, 77, 173);
  gtk_widget_set_size_request (hbox11, 32, 16);

  label22 = gtk_label_new ("Surnom :");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox11), label22, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label22, 64, 16);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_box_pack_start (GTK_BOX (hbox11), entry6, FALSE, FALSE, 0);
  gtk_widget_set_size_request (entry6, 158, 26);

  label16 = gtk_label_new ("<b>Loups</b>");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 30, 120);
  gtk_widget_set_size_request (label16, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label13 = gtk_label_new ("<b>Agneau</b>");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 30, 32);
  gtk_widget_set_size_request (label13, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 56, 104);
  gtk_widget_set_size_request (radiobutton3, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, "Jou\303\251 par l'ordinateur");
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton7, 56, 200);
  gtk_widget_set_size_request (radiobutton7, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton7), TRUE);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5, 56, 144);
  gtk_widget_set_size_request (radiobutton5, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label15 = gtk_label_new ("<b>Choisis ton camp et entre ton nom</b>");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 24, 8);
  gtk_widget_set_size_request (label15, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, "Vrai joueur");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 56, 56);
  gtk_widget_set_size_request (radiobutton4, 160, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton4), TRUE);

  dialog_action_area2 = GTK_DIALOG (jeusimple)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new ();
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (cancelbutton2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image63 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox9), image63, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic ("Annuler");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  okbutton2 = gtk_button_new ();
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (jeusimple), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (okbutton2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image62 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox8), image62, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic ("C'est parti !");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, jeusimple, "jeusimple");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (jeusimple, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (jeusimple, nom_agneau_box, "nom_agneau_box");
  GLADE_HOOKUP_OBJECT (jeusimple, label14, "label14");
  GLADE_HOOKUP_OBJECT (jeusimple, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (jeusimple, label22, "label22");
  GLADE_HOOKUP_OBJECT (jeusimple, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (jeusimple, label16, "label16");
  GLADE_HOOKUP_OBJECT (jeusimple, label13, "label13");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (jeusimple, label15, "label15");
  GLADE_HOOKUP_OBJECT (jeusimple, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT_NO_REF (jeusimple, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (jeusimple, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (jeusimple, image63, "image63");
  GLADE_HOOKUP_OBJECT (jeusimple, label19, "label19");
  GLADE_HOOKUP_OBJECT (jeusimple, okbutton2, "okbutton2");
  GLADE_HOOKUP_OBJECT (jeusimple, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (jeusimple, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (jeusimple, image62, "image62");
  GLADE_HOOKUP_OBJECT (jeusimple, label18, "label18");

  return jeusimple;
}

